# utils/buscadores/orgao_uo.py

# em vez de escrever um a um, realizar uma logica para coletar os valores atraves de st.session_state.base[Órgão (UO)] e depois fazer um set para retirar os duplicados
# e depois fazer um sort para deixar em ordem alfabética
# e depois fazer um list para transformar em lista novamente
# e depois fazer um append para adicionar a lista de opções

opcoes_orgao_uo = [
    "DIVERSOS ÓRGÃOS",
    "GABCIVIL",
    "ALE",
    "TC",
    "AFUNCONTAS",
    "ESCOLA DE CONTAS",
    "FUNEC",
    "TJ",
    "FUNTJ",
    "FUNDESMAL",
    "MP",
    "FEMPEAL",
    "GC",
    "CGE",
    "PGE",
    "DPE",
    "GVG",
    "GOVERNANCA",
    "FUNDO DESENSORIA",
    "ARSAL",
    "FUNPGE",
    "SEPLAG",
    "CARHP",
    "FUNDERH",
    "CEPAL",
    "AMGESP",
    "IPASEAL",
    "ALPREV",
    "FUNPREV",
    "FUNFIN",
    "FUNMIL",
    "FGAP/AL",
    "SEAGRI",
    "IDERAL",
    "FUNDERAL",
    "ITERAL",
    "ADEAL",
    "EMATER",
    "SEADES",
    "FEAS",
    "SECTI",
    "ITEC",
    "FAPEAL",
    "FUNDECTES",
    "INMEQ/AL",
    "SECOM",
    "IZP",
    "SECULT",
    "DITEAL",
    "FUNCULTURA",
    "SSP",
    "PMAL",
    "PCAL",
    "CBMAL",
    "POLCAL",
    "CEDEC",
    "DETRAN",
    "PSPM",
    "PSCBM",
    "FUNESP",
    "FUNDEC",
    "SEDUC",
    "UNEAL",
    "SEFAZ",
    "FUNSEFAZ",
    "AL ATIVOS",
    "SEMARH",
    "IMA",
    "FERH",
    "SEMUDH",
    "SECDEF",
    "PROCON",
    "FUNPROCON",
    "FEDIM",
    "SEINFRA",
    "CASAL",
    "SERVEAL",
    "FEHIS",
    "SESAU",
    "FES",
    "LIFAL",
    "UNCISAL",
    "SETEQ",
    "FTAL",
    "SEDICS",
    "SETUR",
    "SERFI",
    "AFAL",
    "ALGAS",
    "FUNTURIS",
    "FUNERC",
    "JUCEAL",
    "SEPREV",
    "FIA",
    "FEPAD",
    "SERIS",
    "FUNPEAL",
    "SETRAND",
    "DER",
    "SELAJ",
    "FUNESPORTE",
    "SEGOV",
    "SECRIA",
    "PRODUBAN",
    "SETFIN",
    "EGE",
    "RC",
    "ADEPA",
    "DEA"
]
