opcoes_origem_recursos = [
    "Sem Cobertura",
    "Redução/Anulação",
    "Excesso de Arrecadação",
    "Superávit Financeiro",
    "1º NR - Excesso de Arrecadação",
    "2º NR - Excesso de Arrecadação",
    "3º NR - Excesso de Arrecadação",
    "4º NR - Excesso de Arrecadação",
    "1º e 2º NR - Excesso de Arrecadação",
    "Sem Cobertura - Atendido por Redução/Anulação - Emendas",
    "Sem Cobertura - Atendido por Redução/Anulação",
    "Sem Cobertura - Atendido por Superavit Financeiro",
    "Sem Cobertura - Atendido por Excesso de Arrecadação",
    "Sem Cobertura - Atendido pela 1º NR",
    "Sem Cobertura - Atendido pela 2º NR",
    "Sem Cobertura - Atendido pela 3º NR",
    "Sem Cobertura - Atendido pela 4º NR",
    "Excesso de Arrecadação e Superávit Financeiro"
]