
def get_flag_mapping():
    """
    Retorna um dicionário que mapeia os nomes dos países (como aparecem em NO_PAIS)
    para os links das bandeiras correspondentes.
    """
    flag_mapping = {
            
        'Chile': 'https://flagcdn.com/w40/cl.png',
        'França': 'https://flagcdn.com/w40/fr.png',
        'Reino Unido': 'https://flagcdn.com/w40/gb.png',
        'Japão': 'https://flagcdn.com/w40/jp.png',
        'Estados Unidos': 'https://flagcdn.com/w40/us.png',
        'Porto Rico': 'https://flagcdn.com/w40/pr.png',
        'Uruguai': 'https://flagcdn.com/w40/uy.png',
        'Provisão de Navios e Aeronaves': 'https://example.com/path/flag-placeholder.png',
        'Emirados Árabes Unidos': 'https://flagcdn.com/w40/ae.png',
        'Egito': 'https://flagcdn.com/w40/eg.png',
        'Guiné': 'https://flagcdn.com/w40/gn.png',
        'Zimbábue': 'https://flagcdn.com/w40/zw.png',
        'África do Sul': 'https://flagcdn.com/w40/za.png',
        'Itália': 'https://flagcdn.com/w40/it.png',
        'Argentina': 'https://flagcdn.com/w40/ar.png',
        'Rússia': 'https://flagcdn.com/w40/ru.png',
        'Índia': 'https://flagcdn.com/w40/in.png',
        'Alemanha': 'https://flagcdn.com/w40/de.png',
        'Paraguai': 'https://flagcdn.com/w40/py.png',
        'Finlândia': 'https://flagcdn.com/w40/fi.png',
        'Bélgica': 'https://flagcdn.com/w40/be.png',
        'Nigéria': 'https://flagcdn.com/w40/ng.png',
        'Turcomenistão': 'https://example.com/path/flag-placeholder.png',
        'Suíça': 'https://flagcdn.com/w40/ch.png',
        'Singapura': 'https://flagcdn.com/w40/sg.png',
        'Senegal': 'https://flagcdn.com/w40/sn.png',
        'Taiwan (Formosa)': 'https://flagcdn.com/w40/tw.png',
        'Noruega': 'https://flagcdn.com/w40/no.png',
        'Países Baixos (Holanda)': 'https://flagcdn.com/w40/nl.png',
        'Marrocos': 'https://flagcdn.com/w40/ma.png',
        'Portugal': 'https://flagcdn.com/w40/pt.png',
        'México': 'https://flagcdn.com/w40/mx.png',
        'Bolívia': 'https://flagcdn.com/w40/bo.png',
        'Espanha': 'https://flagcdn.com/w40/es.png',
        'Gana': 'https://flagcdn.com/w40/gh.png',
        'Israel': 'https://flagcdn.com/w40/il.png',
        'Uzbequistão': 'https://example.com/path/flag-placeholder.png',
        'Canadá': 'https://flagcdn.com/w40/ca.png',
        'Polônia': 'https://flagcdn.com/w40/pl.png',
        'Venezuela': 'https://flagcdn.com/w40/ve.png',
        'Togo': 'https://flagcdn.com/w40/tg.png',
        'Filipinas': 'https://flagcdn.com/w40/ph.png',
        'Cuba': 'https://flagcdn.com/w40/cu.png',
        'Bulgária': 'https://flagcdn.com/w40/bg.png',
        'Austrália': 'https://flagcdn.com/w40/au.png',
        'Colômbia': 'https://flagcdn.com/w40/co.png',
        'Benin': 'https://flagcdn.com/w40/bj.png',
        'Barbados': 'https://flagcdn.com/w40/bb.png',
        'Quênia': 'https://flagcdn.com/w40/ke.png',
        'Estônia': 'https://flagcdn.com/w40/ee.png',
        'Tanzânia': 'https://flagcdn.com/w40/tz.png',
        'Suécia': 'https://flagcdn.com/w40/se.png',
        'Paquistão': 'https://flagcdn.com/w40/pk.png',
        'Virgens, Ilhas (Americanas)': 'https://flagcdn.com/w40/vi.png',
        'Costa do Marfim': 'https://flagcdn.com/w40/ci.png',
        'Equador': 'https://flagcdn.com/w40/ec.png',
        'Tunísia': 'https://flagcdn.com/w40/tn.png',
        'Coreia do Norte': 'https://flagcdn.com/w40/kp.png',
        'Nova Zelândia': 'https://flagcdn.com/w40/nz.png',
        'Áustria': 'https://flagcdn.com/w40/at.png',
        'Trinidad e Tobago': 'https://flagcdn.com/w40/tt.png',
        'Madagascar': 'https://flagcdn.com/w40/mg.png',
        'Jamaica': 'https://flagcdn.com/w40/jm.png',
        'Coreia do Sul': 'https://flagcdn.com/w40/kr.png',
        'Argélia': 'https://flagcdn.com/w40/dz.png',
        'Irã': 'https://flagcdn.com/w40/ir.png',
        'Dinamarca': 'https://flagcdn.com/w40/dk.png',
        'Ucrânia': 'https://flagcdn.com/w40/ua.png',
        'Moçambique': 'https://flagcdn.com/w40/mz.png',
        'Malásia': 'https://flagcdn.com/w40/my.png',
        'Panamá': 'https://flagcdn.com/w40/pa.png',
        'Síria': 'https://flagcdn.com/w40/sy.png',
        'Virgens, Ilhas (Britânicas)': 'https://flagcdn.com/w40/vg.png',
        'Honduras': 'https://flagcdn.com/w40/hn.png',
        'Arábia Saudita': 'https://flagcdn.com/w40/sa.png',
        'Afeganistão': 'https://flagcdn.com/w40/af.png',
        'Burkina Faso': 'https://flagcdn.com/w40/bf.png',
        'Hong Kong': 'https://flagcdn.com/w40/hk.png',
        'Romênia': 'https://flagcdn.com/w40/ro.png',
        'Belarus': 'https://flagcdn.com/w40/by.png',
        'Irlanda': 'https://flagcdn.com/w40/ie.png',
        'Grécia': 'https://flagcdn.com/w40/gr.png',
        'Antilhas Holandesas': 'https://example.com/path/flag-placeholder.png',
        'Guiana': 'https://flagcdn.com/w40/gy.png',
        'Tailândia': 'https://flagcdn.com/w40/th.png',
        'Mali': 'https://flagcdn.com/w40/ml.png',
        'Sri Lanka': 'https://flagcdn.com/w40/lk.png',
        'Indonésia': 'https://flagcdn.com/w40/id.png',
        'Angola': 'https://flagcdn.com/w40/ao.png',
        'China': 'https://flagcdn.com/w40/cn.png',
        'Eslovênia': 'https://flagcdn.com/w40/si.png',
        'Tadjiquistão': 'https://flagcdn.com/w40/tj.png',
        'Costa Rica': 'https://flagcdn.com/w40/cr.png',
        'Aruba': 'https://flagcdn.com/w40/aw.png',
        'República Dominicana': 'https://flagcdn.com/w40/do.png',
        'Haiti': 'https://flagcdn.com/w40/ht.png',
        'Maurício': 'https://flagcdn.com/w40/mu.png',
        'Azerbaijão': 'https://flagcdn.com/w40/az.png',
        'Gâmbia': 'https://flagcdn.com/w40/gm.png',
        'Iugoslávia': 'https://example.com/path/flag-placeholder.png',
        'Geórgia': 'https://flagcdn.com/w40/ge.png',
        'Iraque': 'https://flagcdn.com/w40/iq.png',
        'Turquia': 'https://flagcdn.com/w40/tr.png',
        'Iêmen': 'https://flagcdn.com/w40/ye.png',
        'Somália': 'https://flagcdn.com/w40/so.png',
        'Chipre': 'https://flagcdn.com/w40/cy.png',
        'Namíbia': 'https://flagcdn.com/w40/na.png',
        'Bahamas': 'https://flagcdn.com/w40/bs.png',
        'Mauritânia': 'https://flagcdn.com/w40/mr.png',
        'Macau': 'https://flagcdn.com/w40/mo.png',
        'Guatemala': 'https://flagcdn.com/w40/gt.png',
        'Croácia': 'https://flagcdn.com/w40/hr.png',
        'Congo': 'https://flagcdn.com/w40/cg.png',
        'Níger': 'https://flagcdn.com/w40/ne.png',
        'Islândia': 'https://flagcdn.com/w40/is.png',
        'Mônaco': 'https://flagcdn.com/w40/mc.png',
        'Cayman, Ilhas': 'https://flagcdn.com/w40/ky.png',
        'Bangladesh': 'https://flagcdn.com/w40/bd.png',
        'Líbano': 'https://flagcdn.com/w40/lb.png',
        'Congo, República Democrática': 'https://flagcdn.com/w40/cd.png',
        'São Tomé e Príncipe': 'https://flagcdn.com/w40/st.png',
        'Cabo Verde': 'https://flagcdn.com/w40/cv.png',
        'Albânia': 'https://flagcdn.com/w40/al.png',
        'El Salvador': 'https://flagcdn.com/w40/sv.png',
        'Tcheca, República': 'https://flagcdn.com/w40/cz.png',
        'Vietnã': 'https://flagcdn.com/w40/vn.png',
        'Hungria': 'https://flagcdn.com/w40/hu.png',
        'Nicarágua': 'https://flagcdn.com/w40/ni.png',
        'Peru': 'https://flagcdn.com/w40/pe.png',
        'Djibuti': 'https://flagcdn.com/w40/dj.png',
        'Sudão': 'https://flagcdn.com/w40/sd.png',
        'Jordânia': 'https://flagcdn.com/w40/jo.png',
        'Líbia': 'https://flagcdn.com/w40/ly.png',
        'Camarões': 'https://flagcdn.com/w40/cm.png',
        'Serra Leoa': 'https://flagcdn.com/w40/sl.png',
        'Malavi': 'https://flagcdn.com/w40/mw.png',
        'Bósnia-Herzegovina': 'https://flagcdn.com/w40/ba.png',
        'Suriname': 'https://flagcdn.com/w40/sr.png',
        'Canárias, Ilhas': 'https://example.com/path/flag-placeholder.png',
        'Omã': 'https://flagcdn.com/w40/om.png',
        'Brasil': 'https://flagcdn.com/w40/br.png',
        'Libéria': 'https://flagcdn.com/w40/lr.png',
        'Guiné-Bissau': 'https://flagcdn.com/w40/gw.png',
        'Etiópia': 'https://flagcdn.com/w40/et.png',
        'Liechtenstein': 'https://flagcdn.com/w40/li.png',
        'Montenegro': 'https://flagcdn.com/w40/me.png',
        'Catar': 'https://flagcdn.com/w40/qa.png',
        'Belize': 'https://flagcdn.com/w40/bz.png',
        'Eslováquia': 'https://flagcdn.com/w40/sk.png',
        'Sérvia': 'https://flagcdn.com/w40/rs.png',
        'Letônia': 'https://flagcdn.com/w40/lv.png',
        'Lituânia': 'https://flagcdn.com/w40/lt.png',
        'Macedônia': 'https://flagcdn.com/w40/mk.png',
        'Moldávia': 'https://flagcdn.com/w40/md.png',
        'Luxemburgo': 'https://flagcdn.com/w40/lu.png',
        'Cocos (Keeling), Ilhas': 'https://flagcdn.com/w40/cc.png',
        'Polinésia Francesa': 'https://flagcdn.com/w40/pf.png',
        'Cazaquistão': 'https://flagcdn.com/w40/kz.png',
        'Palestina': 'https://flagcdn.com/w40/ps.png',
        'Barein': 'https://flagcdn.com/w40/bh.png',
        'Saara Ocidental': 'https://example.com/path/flag-placeholder.png',
        'Camboja': 'https://flagcdn.com/w40/kh.png',
        'Antígua e Barbuda': 'https://flagcdn.com/w40/ag.png',
        'Malta': 'https://flagcdn.com/w40/mt.png',
        'Anguilla': 'https://flagcdn.com/w40/ai.png',
        'Marshall, Ilhas': 'https://flagcdn.com/w40/mh.png',
        'Bouvet, Ilha': 'https://example.com/path/flag-placeholder.png',
        'Guiné Equatorial': 'https://flagcdn.com/w40/gq.png',
        'Mianmar': 'https://flagcdn.com/w40/mm.png',
        'Eritreia': 'https://flagcdn.com/w40/er.png',
        'Santa Lúcia': 'https://flagcdn.com/w40/lc.png',
        'Uganda': 'https://flagcdn.com/w40/ug.png',
        'Granada': 'https://flagcdn.com/w40/gd.png',
        'São Cristóvão e Névis': 'https://flagcdn.com/w40/kn.png',
        'Bermudas': 'https://flagcdn.com/w40/bm.png',
        'Gibraltar': 'https://flagcdn.com/w40/gi.png',
        'São Vicente e Granadinas': 'https://flagcdn.com/w40/vc.png',
        'Tuvalu': 'https://flagcdn.com/w40/tv.png',
        'Dominica': 'https://flagcdn.com/w40/dm.png',
        'Seicheles': 'https://flagcdn.com/w40/sc.png',
        'Botsuana': 'https://flagcdn.com/w40/bw.png',
        'Armênia': 'https://flagcdn.com/w40/am.png',
        'São Martinho, Ilha de (parte francesa)': 'https://example.com/path/flag-placeholder.png',
        'São Bartolomeu': 'https://example.com/path/flag-placeholder.png',
        'Guiana Francesa': 'https://flagcdn.com/w40/gf.png',
        'Curaçao': 'https://flagcdn.com/w40/cw.png',
        'Falkland (Malvinas)': 'https://flagcdn.com/w40/fk.png',
        'Aland, Ilhas': 'https://flagcdn.com/w40/ax.png',
        'Comores': 'https://flagcdn.com/w40/km.png',
        'Cook, Ilhas': 'https://flagcdn.com/w40/ck.png',
        'Sint Maarten': 'https://flagcdn.com/w40/sx.png',
        'Papua Nova Guiné': 'https://flagcdn.com/w40/pg.png',
        'Gabão': 'https://flagcdn.com/w40/ga.png',
        'Maldivas': 'https://flagcdn.com/w40/mv.png',
        'Palau': 'https://flagcdn.com/w40/pw.png',
        'Suazilândia': 'https://example.com/path/flag-placeholder.png',
        'San Marino': 'https://flagcdn.com/w40/sm.png'
    }

    return flag_mapping
