# .streamlit/secrets.toml

GOOGLE_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "sigof-api-drive",
  "private_key_id": "5cf3d70161b2ef4e087f89444a646643cde80b14",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCMvsyeDQaEhlj4\\nFEDiThTfkstyJdEqvBIxvjQOD+S72HiHQdTOvpxrTVCRNgMtzJoRFU1cUmuAkMXg\\nHvo+MtUTNJyp4A69r3mneVvk/nBLacPFBSd65B7S5B2xh6Xm0hY9e16jspXdlmKl\\n6WgOUelwxyHX5kMS/vyrssYqJD1CfHNWGnIUA4LjT5Wgxx4Agbc7oztUxey3hm+L\\nUbu3McWUpk7LAFnofURwp0H9B1OmbmCVJPjTjgh6RTCIi4lsRGbCaKlSzfrNXd01\\nwbO7Wn3Iq+PjOkgigxdrhOrlwE3o0XDhUoMc2Oq0ZmLE3TkGITG+pw3JWqVOMuim\\nJujjfEK9AgMBAAECgf97VWH5HhuYBiKbQc7vK30fGIPZ2J8dKQbIkDm4GOACZq83\\n13hPCLleo2GhM15AbrU+QxcyJQdkoiNul7ayH9lCpdf4WgnmLt7BjeyjvlNTwlrL\\nS2OiokRgiYV7tw1U4hnwcSt9nKu3LGaa/O3c8+qck+Npo13OR6PNfIYqZ5dG/9AF\\nrzyi0gSaIg0Di5yPusaqYpu/WdFyG/l4MvXg67GRXxJJ4KR1RkTAfSyg7RU8eg11\\ndfVzmS6qeKILLdCc3ot0kWZDTFDpmuDPLZVTg6DoN4ijZpU+AgIRR9WJOJX5m+If\\nURwwT9DbyPPn5aSJRoACEKhQwM//ImTSHY/qcIECgYEAwMECylzizhljaT2vPZ72\\n6uK89AKn78aSgC6seSb04X65R18JEpFH52PwMzlPsWXNyEGwHVUyLXk0hPncTXw9\\nH9Y1A0PXfeN3dTVG2S9rfA2T+LoJY13hV4c9SieaJ7x5q5V9DqWL8jpcA22I8TPA\\nZ9MWSX07vfS/RgI3GmAvYJ0CgYEAuu0nt1NmtjVmSwfhhz+tyf6QYQkhJX6KFqRX\nK6bQ+BGq330kPjVy6udVYe9Y3cmwPd4XkQm0heBd7YmS3dbnJRQDgVqf3CZ4tqZD\\noUsoHcdxL8uw1NGmyhN/qC3rbjkNwcyOcBXSGcGg1yKgfhpdUuqKTS6+I7xprhpq\\nnWhKgKECgYB6XEwsMCjeUqmTzk+nW3k9hHAUqnb3NGQdsQNV6U/8sZhmYUL+IXG2\\nxu9dZR1c7NZkMKbfCA1RZqbbX03ldl/LDQ0cJH3wcWyM4CQ4jOy7lFcBxv9cr+Tz\\nzmsu3tLyNKg8LypzGM4tF7T/jBIppAOZJRv5zOEW5f5iL9fRC4wn1QKBgHZ7Q6VL\\n09rCVihQwn67uihClrkq1DuzzUs0t5wPjHzwleI6q/JSZpjGMLR2xVkvMerFDyL7\\nh9UjteWOQe0i/jfeS6p+Cr28FN+Q22UtAix98hxde6QpjxKe8VdkY8nll/ay9cXN\\nzvJMbOpwJFJJ28VmrGrnqdV043dbfyBurmqBAoGAKl5EOhasDJ9FNwpb7QtDVn7U\\nCOTOxAAe49w/7B3UiWcMKu41d45y5e+3T/f/UwWS8W6jTTl9nD5c9CaPIgx7aRv1\\nM+ZWg4Uvn8tG+dI20M6cNZxqdLCFKfNnJiD+UFvttt5+aRtj1svQOcD1ExwdBWi5\\nvcS6zh/fxU3yoPL0hsE=\\n-----END PRIVATE KEY-----\\n",
  "client_email": "sigof-api-drive@sigof-api-drive.iam.gserviceaccount.com",
  "client_id": "104336636402219998480",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sigof-api-drive%40sigof-api-drive.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
[pasta_bases]
FOLDER_ID = "1pRhA-whaSCE-tD_mgyoY8RqzgkTGTv3r" 

[EMAIL]
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
EMAIL_SENDER = "sistemasigof@gmail.com"
EMAIL_PASSWORD = "pjpihszbgajwshda"
DESTINATARIOS = "falcovisk@gmail.com, sop@seplag.al.gov.br, sopseplag@gmail.com"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/180T21xpRhP7eAv3a6NUfpSpgunRRu9wG0smTSeujTzk"
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
type = "service_account"  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
project_id = "sigof-api-sheet"
private_key_id = "d8942e6eb149e05207fddadf38ab7db83423dc1c"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSaDi4x0Qbsz8D\nL+ImZzqlObllNZBdR25KOY+MSw7V9Gccf4JvbpTU3OACibn03BKy9EeH6hSfpQ6o\ninJmFDrchgeXHAefVqT3FvD0U0dS10gavoyWIHQceGzAWBIfgYhLWlxM+5Br0gnM\nHFukNgJ85QawH8x2PW8xn8765zimHPbe6c6pWTVnl35wU6jLHh6pkwoAYvhJEVgx\nhydGDBNi1vQfjxgsRiNAEPLkaqMXIXlHkz35+HXr0AN0nVDCK9QdzZpqSVagr+xH\n0gXljCud29DzzKKAm6grXwfOwNrisUVCBrGcEmc48OW7jiYaNNj/ThQQHxZGQAIE\nlexebPDVAgMBAAECggEABeryh/198kSvglh4Iqc/hpgrtzyQBkUx3wwukjQieGF1\nnYBF7G0i1OvMni2k95HBq7wV/BdpF/7a9dMKxreAnZNJUUFPyY/+AQLLYITRODb9\nch9LnXHYX6I6exfUO7PHp4wSeQYeE02dGcP3rE6GkTfMqmfOouTezrmv6xJXhtdL\nMkiVLI9kGdp7mWFQDUfT51h/+OH5quzYmz93wi1kiKuZ0uBvuUsq8H4nXOUh5rKi\nxWHT7czCw0duhwhTIdskNrQVNIiLjgpn+rXP3tMrOn9v2dII1NDnbEN2WNF9pA50\nVVvCi9Bvx7Mu9xK9SLZ9C+f3UxRWt1+aG5FVvnsfDQKBgQDM1ts4W02aunvSNtBa\nRMPzNO+aMeOT7xc/EpInvKPyIrKnqUFqz6UfmBy/vKg4gMvXjqS7WPcx/HHpHhlw\nBIIh1GRglMP7t6Rb2yVuthdAI5liZIQDNSsuMt1ydT5o3oAPZldPj7WI1srjBviM\nmJH8zSDmxdvrQY3VOiI5Z/9+WwKBgQC2+UrYrtMBelDH+UFz9sGnVObDp0RKp6BE\nmZYYy00Ae8F8D0KBaqb7w64/CY9QOIqkVHbvrNM10ltRqv41YVhRkJsyn4XtKsOp\ncW4CGsWb+ZEo9C/qfsfpq7Aznoa/88ER7RJBVBJNN2/gRtRhmsjc7lV0H3u46f4W\nc1YY1tbUjwKBgClHdyARTj9LK16+ixhV2UMuvMZPHXSXbxDX1jpJyqQmF+ivtC4p\nMDaAufJtu1y/n9SNu2bB0/bvz6jR1wB6+BqHKb9I24HjjSyxqgZ4jZDwW523cd8P\nnOcPew7wz6XkiNwRnLC83jF4T6SWqAn1SR4v3FyFLP9o04NP1svIyHUXAoGBALOX\nwPUps4ZxzjRZ3Pq7qpxZYx+LYCZ+nXp33bF8apoc3m6sc7SfQENBcBgDhB1TQhHF\nre/WDIF5dZSVZ2pxn8R/UTXBCi0dmmsIINgD+w37SZWPCDD8O7CJiitAYDasREca\nEJ76q/QKg8749qDO0nS3ojyWYlO/qFvU3R8IUFjVAoGBAMlNUAVQhq0nsqZIlOMh\n+oKulzp4G7nfyDb6Y75xS6qsikTOxPmYRBIQ8bwYqC581Wj5tOuEbpQ1RQnVbeBC\ni+8Nfc+ec45DY/pntosa2/r26EDmO5UfebnRq8iplOP63l0Fy58Cpjg/n43Vkr5T\nycloShyp9Ui3G1YEhuzFc0IS\n-----END PRIVATE KEY-----\n"
client_email = "sigof-api-sheet@sigof-api-sheet.iam.gserviceaccount.com"
client_id = "104017469747218149724"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sigof-api-sheet%40sigof-api-sheet.iam.gserviceaccount.com"


[users]
"sudo" = "1513"
"admin" = "1513"
"cpof" = "1513"
"geo" = "1513"
"Rebeca Melo" = "x@7ww1#E!d@"
"Felliphy Queiroz" = "4!xT93zL!v"
"Isadora Costa" = "p@7Vw1#E!d"
"Fillipe Fernando" = "Z!8rQa@t3L"
"Romero Cavalcanti" = "n#4Lz$Vm9!"
"SECRETÁRIA EXECUTIVA" = "1513"
"SEPLAG" = "1513"
"SEFAZ" = "1513"
"GABINETE CIVIL" = "1513"
"SEGOV" = "1513"
"externo" = "1513"

[page_access]
"sudo" = ["home", "cadastrar_processo", "canal_resposta_cpof", "dashboards", "relatorio", "visualizar_processos", "historico", "sobre", "repositorio"]
"admin" = ["home", "cadastrar_processo", "canal_resposta_cpof", "dashboards", "relatorio", "visualizar_processos", "historico", "sobre", "repositorio"]
"Rebeca Melo" = ["home", "cadastrar_processo", "relatorio", "dashboards", "visualizar_processos", "historico", "sobre", "repositorio"]
"Felliphy Queiroz" = ["home", "cadastrar_processo", "relatorio", "dashboards", "visualizar_processos", "historico", "sobre", "repositorio"]
"Romero Cavalcanti" = ["home", "cadastrar_processo", "relatorio","dashboards",  "visualizar_processos", "historico", "sobre", "repositorio"]
"Fillipe Fernando" = ["home", "cadastrar_processo", "relatorio", "dashboards", "visualizar_processos", "historico", "sobre", "repositorio"]
"Isadora Costa" = ["home", "cadastrar_processo", "relatorio", "dashboards", "visualizar_processos", "historico", "sobre", "repositorio"]
"geo" = ["home", "cadastrar_processo", "relatorio", "dashboards", "visualizar_processos", "historico", "sobre", "repositorio"]
"SECRETÁRIA EXECUTIVA" = ["canal_resposta_cpof", "home", "sobre", "repositorio", "dashboards", "relatorio"]
"SEPLAG" = ["canal_resposta_cpof", "home", "sobre", "repositorio", "dashboards", "relatorio"]
"SEFAZ" = ["canal_resposta_cpof", "home", "sobre", "repositorio", "dashboards", "relatorio"]
"GABINETE CIVIL" = ["canal_resposta_cpof", "home", "sobre", "repositorio", "dashboards", "relatorio"]
"SEGOV" = ["canal_resposta_cpof", "home", "sobre", "repositorio", "dashboards", "relatorio"]
"cpof" = ["home", "cadastrar_processo", "relatorio", "dashboards", "visualizar_processos", "historico", "sobre", "repositorio"]
"externo" = ["home", "dashboards", "relatorio", "sobre", "repositorio"]

[base_access]
"sudo" = ["Base CPOF", "Base Crédito SOP/GEO", "Histórico CPOF", "Histórico Crédito SOP/GEO", "Base TED", "Histórico TED", "Base SOP/GERAL", "Histórico SOP/GERAL"]
"admin" = ["Base CPOF", "Base Crédito SOP/GEO", "Histórico CPOF", "Histórico Crédito SOP/GEO", "Base TED", "Histórico TED", "Base SOP/GERAL", "Histórico SOP/GERAL"]
"SECRETÁRIA EXECUTIVA" = ["Base CPOF", "Histórico CPOF"]
"SEPLAG" = ["Base CPOF", "Histórico CPOF"]
"SEFAZ" = ["Base CPOF", "Histórico CPOF"]
"GABINETE CIVIL" = ["Base CPOF", "Histórico CPOF"]
"SEGOV" = ["Base CPOF", "Histórico CPOF"]
"Rebeca Melo" = ["Base SOP/GERAL", "Histórico SOP/GERAL"]
"Felliphy Queiroz" = ["Base Crédito SOP/GEO", "Histórico Crédito SOP/GEO", "Base TED", "Histórico TED"]
"Fillipe Fernando" = ["Base Crédito SOP/GEO", "Histórico Crédito SOP/GEO", "Base TED", "Histórico TED"]
"Isadora Costa" = ["Base Crédito SOP/GEO", "Histórico Crédito SOP/GEO", "Base TED", "Histórico TED"]
"Romero Cavalcanti" = ["Base Crédito SOP/GEO", "Histórico Crédito SOP/GEO", "Base TED", "Histórico TED"]
"geo" = ["Base Crédito SOP/GEO", "Histórico Crédito SOP/GEO", "Base TED", "Histórico TED"]
"cpof" = ["Base CPOF", "Histórico CPOF"]